### PR TITLE
Fix parsing a todo with europe date format

### LINKED ISSUE #64: Adding todos with europe-style dates is broken
`t a testing due 9 may` 

The todo is added, but it has no date.

### PR DESCRIPTION
**Pull request by gammons**
* the `hasDue` function was not running, and therefore it was not parsing
the due date.
* Also added the beginnings of a more holistic test approach, using
`app_test.go`.

Closes #64.

### CODE REVIEW

File: todolist/parser.go [hunk 1]
```diff
@@ -86,7 +86,8 @@ func (p *Parser) Contexts(input string) []string {
 func (p *Parser) hasDue(input string) bool {
 	r1, _ := regexp.Compile(`due \w+$`)
 	r2, _ := regexp.Compile(`due \w+ \d+$`)
-	return (r1.MatchString(input) || r2.MatchString(input))
+	r3, _ := regexp.Compile(`due \d+ \w+$`)
+	return (r1.MatchString(input) || r2.MatchString(input) || r3.MatchString(input))
```
Comment (gammons) [inline todolist/parser.go]: this is the actual bugfix here.  The rest of the PR is cleanup / formatting.
